title: Householder Symposium on Numerical Linear Algebra
description: >
 The Householder Symposium on Numerical Linear Algebra is held every three years and 
 provides a venue for established and junior researchers to share their work in an 
 informal setting. Attendance is by invitation only and application information is made 
 available in the fall before each meeting.

show_excerpts: false

# build settings
theme: minima
markdown: kramdown

exclude: ["README.md"]

plugins:
 - jekyll-feed
 - jekyll-seo-tag


