title: Householder Symposium
author:
  name: Anil Damle
  email: damle@cornell.edu
# description: The Householder Symposium on Numerical Linear Algebra is held every three years

# build settings
theme: minima
markdown: kramdown

exclude: ["README.md"]


